[기현] 야구 게임
Java-Bom/base-ball pull request #3
Opened 2020-06-18 08:07 UTC by BangKiHyun

<img width="1669" alt="야구 게임 다이어그램" src="https://user-images.githubusercontent.com/43977617/84994577-d7f2c600-b185-11ea-99da-6b0808adc9c4.png">

야구 게임 기능 구현했습니다!

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/BaseBallGameApplication.java
> +        while (!solved) {
이건 게임 전반의 가장 중요한 상태값이라고 생각해
이 상태와 이 상태를 바꾸는 행동을 하는 객체를 하나 두는게 나아보여

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/WinningGameNumbers.java
> +public class WinningGameNumbers {
ClientGameNumbers랑 많이 중복된다고 생각해.
그냥 GameNumbers 하나로 답과 입력 숫자들을 관리할 수 있지않을까? 
로또티켓에서 1등티켓 객체를 따로 만들지 않았던것처럼.

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResult.java
> +    }
```suggestion
    public static MatchedResult findResult(final boolean allMatchStatus, final boolean anyMatchStatus) {
        if (allMatchStatus) {
            return STRIKE;
        }
        if (anyMatchStatus) {
            return BALL;
        }
        return OUT;
    }
```
이건 굳이 메소드 나눌필요가 없을듯??

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +    }
isValid가 메소드로 굳이 빠질 필요없어보여. 
또, isValid 안에있는 불린값은 VALID 하지 않은애인거같은데.. 숫자가 최소보다 작거나 최대보다 크면 VALID 한게 아니잖아? 반대로 되어있네.
if(isValid)라는 말은 이게 제대로됬다면~~?? if블록 실행해야지~~ 라는 뜻인거같은데
오히려 여기서 throw를 던져서 ??이게뭐여 이런느낌이야

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +
이건 가장 밑으로 내리는게 컨벤션이야

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +
밑에있는 오바라이드 메소드가 이놈꺼인줄알앗어

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +
또, ArrayList 만들때 개수가 정해져있으면 생성자에 숫자를 명시해주는게 좋아. 내부적으로 이놈은 배열을 쓰고있어서 디폴드로 100인가(확실치않음) 설정되어있거든. 캐싱 자체가 메모리,성능을 가져가려고 하는거라 생각해. 그러려면 ArrayList자체도 낭비되는 메모리가 없어야된다고봐.

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/valid/GameNumbersValidator.java
> +public class GameNumbersValidator {
음... 검증로직이 따로 클래스로 삐져나온건 난 굉장히 좋지 않다고봐. 클래스의 응집도를 떨어뜨린다고 생각해.
검증로직을 내가해야되는데 엉뚱한놈이 하고있는 느낌이랄까?

2020-06-18 18:58 UTC, nightmare73 commented on src/test/java/com/javabom/baseballgame/domain/domain/machine/FixedNumbersGenerator.java
> +}
테스트코드에 FixedNumberGenerator를 따로 만듦으로써 생기는 단점은 무엇일까?

2020-06-18 18:58 UTC, nightmare73 commented on src/test/java/com/javabom/baseballgame/domain/domain/number/GameNumberTest.java
> +        int gameNumber = -1;
난 10일때도 테스트해줘야한다고 생각해

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/machine/RandomGameNumbersGenerator.java
> +    private static final List<GameNumber> gameNumbers = collect();
딱 이줄만 봤을때 collect()가 무슨일을 하는지는 메소드를 봐야만 알거같아.
나라면 createGameNumbers 등 더 구체적인 이름을 썼을거같아

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/ClientGameNumbers.java
> +    }
처음보면 둘을 구분짓기 힘들거같아.
더 구체적인 네이밍이 필요해보여

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/ClientGameNumbers.java
> +    }
테스트코드에만 사용되는 메소드는 지양하는게 좋아

2020-06-18 18:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/OrderGameNumber.java
> +    }
생성자가 퍼블릭으로 존재하는데, of라는 객체를 생성해주는 static 메서드의 존재의미를 모르겠어

2020-06-19 04:57 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/BaseBallGameApplication.java
> +        while (!solved) {
아 그렇구나 수정해볼게! 고마워!

2020-06-19 05:02 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/WinningGameNumbers.java
> +public class WinningGameNumbers {
아 맞아 ClientGameNumbers랑 중복되는 부분이 있어서 하나로 만들까 했는데 사용자가 입력한 값이랑 컴퓨터가 뽑은 값이랑 의미하는 바가 다르다고 생각해서 나눴어!
그래서 Validator랑 Converter가 생겼는데 하나로 합치는게 나을까?

2020-06-19 05:10 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +    }
아! 반대로 되있네! 만약에 if(isNotRange)로 되어있으면 throw를 던질수 있다 라고 생각할 수 있을까?
gameNumber < MIN_NUMBER || gameNumber > MAX_NUMBER가 무엇을 의미하는지 명확하게 알려주고 싶어서!

2020-06-19 05:13 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +
앗! 고마워! 수정할게!

2020-06-19 05:13 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResult.java
> +    }
인텐트 문제때문에 나눴는데 아닌가??

2020-06-19 05:19 UTC, BangKiHyun commented on src/test/java/com/javabom/baseballgame/domain/domain/number/GameNumberTest.java
> +        int gameNumber = -1;
앗! 그러네! 고마워!

2020-06-19 05:20 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/ClientGameNumbers.java
> +    }
아 그러네! 좀더 구체적으로 바꿔볼게!

2020-06-19 05:22 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/OrderGameNumber.java
> +    }
아 그러네 생성자가 public일 필요가 없구나! 고마워!

2020-06-19 05:23 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/machine/RandomGameNumbersGenerator.java
> +    private static final List<GameNumber> gameNumbers = collect();
좀더 생각해서 네이밍을 해볼게!

2020-06-19 05:24 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/valid/GameNumbersValidator.java
> +public class GameNumbersValidator {
ClientGameNumbers와 WinningGameNumbers에 같은 검증로직이 생겨서 둘을 합치면 필요가 없긴한데 고민이야!

2020-06-19 14:58 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResult.java
> +    }
인덴트에 문제없어보이는데 ??

2020-06-19 14:59 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +    }
저 비교하는 줄 박아도 가독성엔 문제없다고봐

2020-06-19 15:00 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/domain/number/OrderGameNumber.java
> +    }
음?? 나는 스태틱메소드를 지우는게 낫다고봐

2020-06-20 08:21 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResult.java
> +    }
아 이거 인텐트 1이구나!

2020-06-20 08:25 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/OrderGameNumber.java
> +    }
아 그러네 바로 넘겨주면되는구나

2020-06-23 11:29 UTC, Gobukgol commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResults.java
> +        Map<MatchedResult, Integer> matchedResults = new HashMap<>();
Map의 Key값이 Enum의 인스턴스라면 Map의 구현체를 EnumMap으로 써도 좋아요.
HashMap 과 다르게 해싱하는 과정이 따로 필요치 않아서 성능상에도 이점이 있고, EnumMap 자체가 Key 값의 타입 안정성을 보장하기도 해요!

2020-06-23 11:29 UTC, Gobukgol commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResults.java
> +        return matchedResults.get(matchedResult);
이부분은 Map의 getOrDefault 메소드를 사용해도 좋을것 같아요

2020-06-23 11:29 UTC, Gobukgol commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +        static final List<GameNumber> CACHE;
이 Cache의 자료구조를 List 대신 다른건 어떨까요? 

제 개인적인 생각인데 숫자 1에 해당하는 값을 가져올때  가져오려는 GameNumber 가 숫자 1과 맞는 GameNumber를 가져오는 것인데 List의 경우 리스트에서 인덱스 1에 해당하는 GameNumber를 가져오는 것이니까 의미가 일치하는 자료구조는 아닌것 같다는 생각이 들어서요!  만약 야구 게임의 숫자가 0 ~ 9 가 아니라 1 ~ 9 였다면 어떻게 되었을까요?

2020-06-23 11:29 UTC, Gobukgol commented on src/test/java/com/javabom/baseballgame/domain/domain/result/MatchedResultsTest.java
> +                MatchedResult.valueOf(thirdResult));
String 타입말고 MatchedResult 로 하면 해당하는 열거타입으로 들어가요.

2020-06-24 03:44 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/result/MatchedResults.java
> +        Map<MatchedResult, Integer> matchedResults = new HashMap<>();
와 좋은정보 감사해요! 적용해볼게요!

2020-06-24 03:45 UTC, BangKiHyun commented on src/main/java/com/javabom/baseballgame/domain/domain/number/GameNumber.java
> +        static final List<GameNumber> CACHE;
아 그렇네요! 좀더 생각해서 수정해볼게요! 감사합니다!

2020-06-24 03:46 UTC, BangKiHyun commented on src/test/java/com/javabom/baseballgame/domain/domain/result/MatchedResultsTest.java
> +                MatchedResult.valueOf(thirdResult));
아! 감사합니다!!

2020-06-24 18:05 UTC, pci2676 requested changes
다른사람들 리뷰 먼저 반영해보면 좋을듯
그리고 다른사람 코드도 한번 보면 더 좋을듯 ㅎ

2020-06-24 18:05 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/domain/utils/OrderGameNumberConverter.java
> +public class OrderGameNumberConverter {
굳이 필요한가 싶어 
OrderGameNumber 에서 리스트를 주입받아서 해당기능을 수행해도 상관없지 않나 싶어서

2020-06-24 18:05 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/domain/machine/GameNumberMachine.java
> +        return new ClientGameNumbers(clientGameNumber);
```suggestion
    public ClientGameNumbers getClientGameNumbers(List<String> strClientGameNumber) {
        return strClientGameNumber.stream()
                .map(GameNumber::of)
                .collect(collectingAndThen(toList(),ClientGameNumbers::new));
    }
```
소소한 팁..

2020-07-11 02:45 UTC, merged