숫자야구 - Step1
Java-Bom/base-ball pull request #5
Opened 2020-06-23 07:47 UTC by csbsjy

![image](https://user-images.githubusercontent.com/47847993/85375340-1cf56e80-b571-11ea-8eed-334530b21a23.png)

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +
static 메서드에서 생성자를 부르는데, 이게 바로 생성자를 부르는 것과 어떤 차이점이 있는지 궁금해요!

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    }
InputView 에서 3개만 딱 잘라서 가져오는데, 이러면 
1,1,2,3입력시 에러를 거르지 못하는걸 확인했습니다. 1,1,2 를 가져오지만 순서가 1,2,3로 입력되면서 서로 다른 공이 되어버린거같아요.
Set 의 단점인거같아요!

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +
오왕 이걸 스트림으로 할 수가 있엇네요... 완전굿인거같아요 👍👍

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/view/InputView.java
> +                .collect(collectingAndThen(toSet(), BaseballNumbers::new));
요기서 1,1,2,3 같은애들을 걸러주지 못하구있어요.
여기서 3개 검증로직 추가하는것도 좋을거같은데.. 인풋뷰라서 검증로직을 추가하는게 맞는건지 잘 모르겠네요.

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/BaseballGameApplication.java
> +        int tryCount = 0;
저는 이 값들이 BaseballGame 객체에 들어가서 게임 전체의 상태를 갖고있는게 나은거같아요.
BaseballGame에게 caculate 할때 마다 tryCount 상태가 1씩 증가하고,
BaseballGame에게 이게 틀렸는지 맞았는지 물어봐서 틀렸으면 또 질문하는 메세지를 보내고.
이렇게 래핑하면 이 상태값들을 의미있게 가지고있을거라 생각합니다!

2020-06-23 09:04 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +    private final int value;
저는 BaseballNumber 자체에는 순서를 부여하지 않고 그저 숫자만 들고있게 하고, 새로운 IndexBaseballNumber를 만들어서 그 안에 Number객체와 인덱스 번호를 부여했어요. 저는 숫자 자체에는 처음부터 순서를 보장할 필요가 없다고 생각해서요!
어떻게 생각하시나요?? 의견 궁금합니당

2020-06-23 14:52 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +
객체를 생성하는 메서드에 이름을 부여할 수 있다는 장점이있는데요, 이 경우에는 new BaseballNumber(Order.of(1), 1) 이런식으로 쓰는것보다 of를 사용하는게 더 가독성있어보여서 그렇게 했어요~

2020-06-23 14:52 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    }
ㅎㅎ InputView 검증을 아예 안해써여 ,, 1,1,2 를 못거르는건 몰랐네요! equals 구현해서 걸러질줄 ,,!

2020-06-23 14:53 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/view/InputView.java
> +                .collect(collectingAndThen(toSet(), BaseballNumbers::new));
View에서 도메인을 뱉어주는걸로 가정하고 도메인위주로 구현하기로해서 이렇게했어요! 검증로직 생각안했어요!

2020-06-23 14:57 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +    private final int value;
숫자야구게임의 야구공이라는 도메인객체이기때문에 순서와 숫자를 함께가지고있어도 괜찮다고생각합니다. 혁님코드 아직 안봤는데 그러면 Number가 단순히 int값 래핑에 지나지않나요?

2020-06-23 14:59 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +
https://javabom.tistory.com/1?category=833277

2020-06-23 15:02 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    }
아아 못거르는게 맞네여 ㅋㅋㅋ TODO로해놓고 까먹어써여 ㅠㅠ

2020-06-23 15:11 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +
오... 그러네요 블로그 정리 잘되어있네요! 잘봤습니다 :)

2020-06-23 15:15 UTC, nightmare73 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +    private final int value;
음 그렇군요. 저는 따로 분리는 해놓았지만 BaseballNumber 자체에는 검증이랑 캐싱이 되어있어서 단순 래핑은 아니라고 생각했어요. 뭔가 고민점이 생겼네요. 나름 잘 분리했다고 생각했는데, 좀더 생각을 해봐야할거같아요.

2020-06-23 15:17 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +    private final int value;
오 저 0-9까지 검증 그걸 아예 놓치고있었어여 ㅋㅋㅋ 혁님처럼 하는게 더 좋을것같아여

2020-06-24 17:21 UTC, pci2676 requested changes
어플리케이션이 터지는 부분발견!
찾아서 수정해주세요~

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +        if (number < START_BOUND || number > END_BOUND) {
9넣으면 터진다!

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/BaseballGame.java
> +    }
위 로직 BaseballNumbers 내부에서 하지 않은 이유가 있어?

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +        if (values.size() != COUNT) {
```suggestion
        this.values = values;
        if (this.values.size() != COUNT) {
```
`this` 써주는게 안전하지 않을까?

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +        if (number < START_BOUND || number > END_BOUND) {
게임 시작할때 컴퓨터가 9뽑으면 그때도 터지네 ㅎㅎ

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/domain/RandomBaseballNumbersGenerator.java
> +        Collections.shuffle(numbers);
이렇게 되면 멀티 스레드 환경에서 exception 발생할거야
여려명이 numbers를 셔플하면서 어떠한 컴퓨터는 중복된 번호가 발생할듯!

2020-06-24 17:21 UTC, pci2676 commented on src/main/java/com/javabom/baseballgame/view/OutputView.java
> +        return outputs.countOf(STRIKE) != COUNT;
이거 뷰가 해줘야하는 일인가 싶어 `count = 3` 이라는 것도 도메인 정보라고 봐야하는거 아닌가 싶거든
print가 반환값을 가지고 있는 것도 조금 어색해 보이구..!

2020-06-25 05:33 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumber.java
> +        if (number < START_BOUND || number > END_BOUND) {
허걱스

2020-06-25 05:44 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/BaseballGame.java
> +    }
뭔가 BaseballNumbers가 BaseballNumbers를 받아서 결과를 계산하게되면 계산기준(시스템이 생성한 숫자)과 사용자의 공을 명확히 구분하기 힘들지 않을까 하고 생각했는데 또 다시보니 BaseballNumbers가 계산하는게 맞는거같앙 getValues를 굳이 하지 않는게 더 좋아보이넹

2020-06-25 11:03 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +                .map(this::calculate)
getValues() 는 내부에서만 사용되니 해당메소드는 삭제하고, 그냥 value를 접근해도 좋을거같아요.
아마 밀어넣으시다가 발견 못하신듯 !!

2020-06-25 11:03 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/Order.java
> +
이 경우에는 cache[0] 가 낭비되니 Map으로 했어도 좋을거같아요.

2020-06-25 11:03 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/OrderedBaseballNumber.java
> +    }
정적 팩토리 메소드로 지원을 하니, 아예 인풋을 둘다 int로 받고 이 내부에서 각각의 of로 찾아서 넣어주는것도 괜찮겠다 라는 생각을 했어요.

2020-06-25 11:03 UTC, malibinYun commented on src/main/java/com/javabom/baseballgame/domain/OrderedBaseballNumber.java
> +    }
```suggestion
    public static OrderedBaseballNumber of(final int order, final int number) {
        return new OrderedBaseballNumber(Order.valueOf(order), BaseballNumber.of(number));
    }
```

2020-06-25 12:17 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/OrderedBaseballNumber.java
> +    }
이건 뭔가 취향?의 차이인거같아여 
저같은경우는 도메인끼리 움직이는 것은 선호해서 일부러 도메인 로직은 매개변수도 도메인을 받도록 하는걸 택했는데, 이번 넥스트스탭 리뷰때도 사용성을 위헤 기본형을 받는 메서드도 오버로딩하는건 어떤가 하는 리뷰를 받기도 했거든여 ㅋㅋㅋ

2020-06-25 12:19 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/domain/Order.java
> +
음 Map 생성비용 + cache[0] 낭비 vs 배열의 빠른 접근속도
의 차이로 생각하면 ,, 저는 후자를 선택하지 않을까 싶어여 ,,!

2020-06-25 12:45 UTC, csbsjy commented on src/main/java/com/javabom/baseballgame/BaseballGameApplication.java
> +        int tryCount = 0;
아 tryCount는 반영을 안했는데요, BaseballGame 객체는 게임을 실행하는 역할만 담당하도록 설계했고, 시도횟수는 게임을 실행을 요청하는 클라이언트 객체가 알면된다고 생각했습니다~

2020-06-25 13:36 UTC, mjung1798 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    public BaseballNumbers(final Set<OrderedBaseballNumber> values) {
아래는 of를 이용해서 객체를 생성하고, 이거는 생성자로 객체를 생성하는 것 같은데, 이왕 정적 팩터리메서드 사용하는거면 둘다 의미살려서 정적 팩터리메서드로 만드는거 어때?
위에는 수동으로 유저가 생성할 때 사용하는거고, 아래는 random으로 생성하는 건 알겠는데, 
아무래도 생성할 때겹치는 로직이 있지않나? 좀더 공통되게 작성하면 좋을 것 같아

2020-06-25 13:36 UTC, mjung1798 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    public BaseballNumbers(final Set<OrderedBaseballNumber> values) {
randomGenerator에서 Set으로 생성하면 안되나?

2020-06-25 13:48 UTC, mjung1798 commented
전체적으로 테스트코드가 부족한 것같아. 코드가 조금 복잡한 느낌이있는데 코드를 좀더 쪼개면 테스트 검증도, 좀더 직관화도 잘 될 것 같아.
예를 들자면, stream을 쓰는건 좋지만 calculate 메서드 안에 stream이 여러개 쓰이고, 그안에 private 메서드로 또 메서드 참조가 일어나니까 가독성이 떨어지고, 오히려 메서드 하나가 많은 일을 하는느낌을 받게돼
음 내가 못하는 걸수도.. 일단 지금도  커멘트가 넘 많아서 오프에서 리뷰 받으면 한번 리팩토링 하고나서 볼께
앗 그리구 폴더링 좀 더 세분화 해줬으면 좋겠어여

2020-06-25 13:50 UTC, mjung1798 commented on src/main/java/com/javabom/baseballgame/domain/BaseballNumbers.java
> +    public BaseballGameOutputs calculate(final BaseballNumbers baseballNumbers) {
calculate라는 이름이 너무 많이 나와서 모호한 것 같아! 이름을 좀 고민해봅시당..ㅎㅅㅎ

2020-07-11 02:46 UTC, merged